server:
  port: 8084

spring:
  cloud:
    gateway:
      routes:
      - id: HOTEL-SERVICE
        uri: lb://HOTEL-SERVICE
        predicates:
        - Path=/hotels/**,/staffs/**
      
      - id: RATING-SERVICE  
        uri: lb://RATING-SERVICE 
        predicates:
         - Path=/ratings/**
      - id: USER-SERVICE  
        uri: lb://USER-SERVICE 
        predicates:
        - Path=/users/**

eureka:
   client:
     fetch-registry: true
     register-with-eureka: true
     service-url:
        defaultZone: http://localhost:8761/eureka     
   instance:
     prefer-ip-address: true