server:
  port: 8085

eureka:
    client:
      fetch-registry: true
      register-with-eureka: true
      service-url:
         defaultZone: http://localhost:8761/eureka     
    instance:
      prefer-ip-address: true


spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ajind033/microservice-config-practice
          clone-on-start: true