services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: 'hotelDB'
      # So you don't have to use root, but you can if you like
      POSTGRES_USER: 'user'
      # You can use whatever password you like
      POSTGRES_PASSWORD: 'pass'
    ports:
      # <Port exposed> : <POSTGRES Port running inside container>
      - '5432:5432'
    expose:
      # Opens port 5432 on the container
      - '5432'
      # Where our data will be persisted
    volumes:
      - postgres-db:/var/lib/postgresql/data
# Names our volume
volumes:
  postgres-db:
