server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hotelDB
    username: user
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
   hibernate:
      ddl-auto: update
   show-sql: true

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka			
  instance:
    prefer-ip-address: true